<br>
<table border="0" width="100%" cellspacing="0" cellpadding="2">
    <tr>
        <td align="center" class="smallText">
            osCommerce Online Merchant Copyright &copy; 2007 <a href="http://www.oscommerce.com" target="_blank">osCommerce</a><br>
            osCommerce provides no warranty and is redistributable under the <a href="http://www.fsf.org/licenses/gpl.txt" target="_blank">GNU General Public License</a>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->image(MVC_IMAGE_DIR . 'pixel_trans.gif', array('width' => 1, 'height' => 5));?></td>
    </tr>
    <tr>
        <td align="center" class="smallText">Powered by <a href="http://www.oscommerce.com" target="_blank">osCommerce</a></td>
    </tr>
</table>
