<?php echo $messages?>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td colspan="2" align="center" class="main">
            <a href="orders.php">all</a> |
            <?php echo $ordersStats . $ordersForms;?>
        </td>
    </tr>
    <tr class="headerBar">
        <td class="headerBarContent">&nbsp;&nbsp;<?php
            echo '<a href="' .
                tep_href_link(FILENAME_DEFAULT, '', 'NONSSL') .
                '" class="headerLink">' . HEADER_TITLE_ADMINISTRATION .
                '</a> &nbsp;|&nbsp; <a href="' . tep_catalog_href_link()
                . '" class="headerLink">' .
                HEADER_TITLE_ONLINE_CATALOG . '</a> &nbsp;|&nbsp;
                <a href="http://www.oscommerce.com" class="headerLink">' . HEADER_TITLE_SUPPORT_SITE . '</a>'; ?>
        </td>
        <td class="headerBarContent" align="right"><?php echo (tep_session_is_registered('admin') ? 'Logged in as: ' . $admin['username']  . ' (<a href="' . tep_href_link(FILENAME_LOGIN, 'action=logoff') . '" class="headerLink">Logoff</a>)' : ''); ?>&nbsp;&nbsp;</td>
    </tr>
</table>