<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title><?php echo $this->title;?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.css">
    <link rel="stylesheet" href="<?php echo STATIC_PREPEND . '/app' . MVC_APP_NAMESPACE_FOLDER . '/public/css/style.css'?>">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src=""></script>
    <?php echo $this->pageJs;?>
</head>
<body>
        <?php include $this->view ?>
        <div id="info_message" class="alert alert-info alert-block abs-info"></div>
        <div id="error_message" class="alert alert-danger alert-block abs-info"></div>
</body>
</html>
