<div id="limisan_ad">
    <ul>
        <li>
            <a href="<?= tep_href_link(FILENAME_PRODUCT_INFO, 'products_id=' . 55856); ?>"></a>
            <div class="box01">Limisan</div>
            <div class="img01"></div>
        </li>
        <li>
            <a href="<?= tep_href_link(FILENAME_PRODUCT_INFO, 'products_id=' . 55858); ?>"></a>
            <div class="box02">Limisan SPORT</div>
            <div class="img02"></div>
        </li>
        <li>
            <a href="<?= tep_href_link(FILENAME_PRODUCT_INFO, 'products_id=' . 55857); ?>"></a>
            <div class="box03">Limisan PRO</div>
            <div class="img03"></div>
        </li>
    </ul>
</div>