<?php
$request_type = \Macaw::getKey('request_type');
$currencies = \Macaw::getKey('currencies');
$cart = \Macaw::getKey('cart');
$stripped_header = \Macaw::getKey('stripped_header');
$freeShippingNl = \Macaw::getKey('freeShippingNl');
$language = \Macaw::getKey('language');
$PHP_SELF = \Macaw::getKey('PHP_SELF');
$danonewinkel = \Macaw::getConfig('is_danonwinkel');
$solrVariantRetest = \Macaw::getConfig('solrVariantRetest');
$mobileUrl = \Macaw::getKey('mobileUrl');
$sociomantic = \Macaw::getKey('sociomantic');

$messageStack = \Macaw::getKey('messageStack');
$header_variant = \Macaw::getConfig('header_variant');
$skin = \Macaw::getKey('skin');
$enable_page_cache = \Macaw::getKey('enable_page_cache');
$breadcrumb = \Macaw::getKey('breadcrumb');
$languages_id = \Macaw::getKey('languages_id');
$seo_urls = \Macaw::getKey('seo_urls');
$timeZone = new DateTime('Europe/Amsterdam');
$time_Amsterdam = strtotime($timeZone->format('H:i'));
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html <?php echo HTML_PARAMS; ?>>
<head>
    <link href="https://plus.google.com/100831886366776414916" rel="publisher" />
    <title><?php echo $this->title;?></title>
    <?php if (isset($description)):?> <meta name="Description" content="<?php echo $description;?>"><?php endif?>
    <?php if (isset($keyw)):?> <meta name="Keywords" content="<?php echo $keyw;?>"><?php endif?>
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET;?>">
    <link rel="shortcut icon" href="<?php echo STATIC_PREPEND;?>favicon.ico" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <base href="<?php echo (($request_type == 'SSL') ? HTTPS_SERVER : HTTP_SERVER) . DIR_WS_CATALOG; ?>">
    <?php echo $this->canonicalUrl;?>
    <link rel="stylesheet" type="text/css" href="<?php echo STATIC_PREPEND; ?><?php echo getStylesheet() ?>">
    <link rel="stylesheet" href="<?php echo STATIC_PREPEND; ?>includes/javascript/base/jquery.ui.all.css" type="text/css">
    <!--header_libraries_js.php-->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
        var JqueryScriptStatic   = '\<script src="<?php echo STATIC_PREPEND; ?>includes/javascript/jquery.1.11.0.min.js"\>\</script\>';
        var JqueryScript         = '\<script src="includes/javascript/jquery.1.11.0.min.js"\>\</script\>';
        window.jQuery || document.write(JqueryScriptStatic);
        window.jQuery || document.write(JqueryScript);

    </script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

    <script type="text/javascript">
        var JqueryUIScriptStatic = '\<script src="<?php echo STATIC_PREPEND; ?>includes/javascript/jquery-ui.min.1.10.4.js"\>\</script\>';
        var JqueryUIScript       = '\<script src="includes/javascript/jquery-ui.min.1.10.4.js"\>\</script\>';
        window.jQuery.ui || document.write(JqueryUIScriptStatic);
        window.jQuery.ui || document.write(JqueryUIScript);
    </script>
    <script src="<?php echo STATIC_PREPEND; ?>includes/javascript/ui/i18n/jquery.ui.datepicker-nl.js"></script>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    <script type="text/javascript" src="<?php echo $static_prepend; ?>includes/javascript/css_browser_selector.min.js"></script>
    <!--end of header_libraries_js.php-->
    <script type="text/javascript" src="<?php echo STATIC_PREPEND; ?>includes/javascript/javafunct.js"></script>
    <script type="text/javascript">
        $(function(){
            $(".prod-box-min-five").mouseover(function(){
                $(this).find(".leverbaar").removeClass("hide");}).mouseout(function(){
                $(this).find(".leverbaar").addClass("hide");
            })
            $("#tabs").tabs();
        });
        function changeSearchSorts(){
            var sTop = document.body.scrollTop+document.documentElement.scrollTop;
            $(document.body).append(loadingDiv);
            $("#loading").css("top",(sTop + document.documentElement.clientHeight/2 - 100) + "px");
            document.quick_find3.submit();
        }
    </script>
    <!--header_js.php-->
    <script src="//www.google-analytics.com/cx/api.js?experiment=c4kxUjBdRAKFFCWVaWAO5Q"></script>
    <script>cxApi.setChosenVariation(0);</script>
    <script type="text/javascript">
        $.fn.__tabs = $.fn.tabs;
        $.fn.tabs = function (a, b, c, d, e, f) {
            var base = window.location.href.replace(/#.*$/, '');
            $('ul>li>a[href^="#"]', this).each(function () {
                var href = $(this).attr('href');
                $(this).attr('href', base + href);
            });
            $(this).__tabs(a, b, c, d, e, f);
        };

        <!-- HitTail Code -->
        (function(){ var ht = document.createElement('script');ht.async = true;
            ht.type='text/javascript';ht.src = '//111160.hittail.com/mlt.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ht, s);})();
    </script>
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PHNXPG" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PHNXPG');</script>
    <script type="text/javascript" src="<?php echo STATIC_PREPEND; ?>includes/javascript/main.js"></script>
    <!--end header_js.php-->
    <?php echo $this->pageJs;?>
</head>
<body>
<!-- header -->
<script type="text/javascript">
    var WRInitTime=(new Date()).getTime();
</script>
<!--[if lt IE 7]>
<script defer type="text/javascript" src="<?php echo $static_prepend; ?>javascript/pngfix.js"></script>
<![endif]-->

<script type="text/javascript">var _elapsedTimeStatusIndicator = 'stringValueDeclaredBeforeLoadingLiveChatJavaScript';</script>
<div id="wrapper" class="page-wrapper">
    <div class="page-container">
        <div id="header">
            <div id="logo">
                <?php
                echo '<a href="' . tep_href_link(FILENAME_DEFAULT, 'skin=none') . '" class="logo">' . STORE_NAME . '</a>';
                switch ($_GET['skin']) {
                    case "biodavitymea":
                        echo '<a href="' . tep_href_link("index.php", 'manufacturers_id=' . 31) . '" class="bional">' . STORE_NAME . '</a>';
                        echo '<a href="' . tep_href_link("index.php", 'manufacturers_id=' . 51) . '" class="davitamon">' . STORE_NAME . '</a>';
                        echo '<a href="' . tep_href_link("index.php", 'manufacturers_id=' . 423) . '" class="yema">' . STORE_NAME . '</a>';
                        break;
                    case "drfix":
                        echo '<a href="/sur-plus-dr-fix-m-539.html" class="skin">' . STORE_NAME . '</a>';
                        break;
                    default:
                        if ($skin_page)
                            echo '<a href="' . $skin_page . '"  class="skin">' . STORE_NAME . '</a>';
                        else
                            echo '<a href="index.php"  class="skin">' . STORE_NAME . '</a>';
                        break;
                }
                ?>
                <?php
                if ($_GET['skin'] == 'nhs') {
                    $referrer = '';
                    $website = '';
                    if (isset($_GET['referrer']) && !empty($_GET['referrer'])) {
                        $referrer = rawurlencode($_GET['referrer']);
                    }
                    if (isset($_GET['website']) && !empty($_GET['website'])) {
                        $website = rawurlencode($_GET['website']);
                    }
                    $back_urls = $_SESSION['back-urls'];
                    if (!$back_urls) {
                        $back_urls = array();
                    }
                    $back_urls[] = $_SERVER['REQUEST_URI'];
                    end($back_urls);
                    $last_back_url = key($back_urls);
                    $_SESSION['back-urls'] = $back_urls;
                    ?>
                    <a class="button-nhs button-back"
                       style="display:none;"><span><span>Keer terug naar de e-shop van Nestl &eacute; Health Science</span></span></a>
                    <script type="text/javascript">
                        //<![CDATA[
                        var previous_url = '<?php echo $referrer ?>';
                        var website = '<?php echo $website ?>';
                        if (previous_url != '' && website != '') {
                            document.cookie = 'dodnhs-url=https://eshop.nestlehealthscience.nl/' + website + '/' + previous_url + '; path=/;';
                        }
                        ;
                        var get_url = document.cookie.replace(/(?:(?:^|.*;\s*)dodnhs-url\s*\=\s*([^;]*).*$)|^.*$/, "$1");
                        if (get_url) {
                            jQuery('.button-nhs.button-back').show().attr('href', get_url + '?backurl=<?php echo $last_back_url ?>');
                        }
                        ;
                        //]]>
                    </script>
                    <?php
                    echo '<div class="header-page-title">Bestelpagina</div>';
                }
                ?>
                <?php
                if (strpos(getStylesheet(), 'moederdag') !== false) {
                    echo '<a href="kadowinkel-c-596.html" class="sublogoLnk">Alles voor moeder...</a>';
                }
                if (strpos(getStylesheet(), 'vaderdag') !== false) {
                    // echo '<a href="vaderdag.php" class="sublogoLnk">Alles voor vader...</a>';
                }
                ?>

            </div>

            <div id="menuAccount" <?php if (!tep_session_is_registered('customer_id')) { ?>class="menu-login"
                 <?php }else{ ?>class="menu-account"<?php } ?>>
                <?php if ($_GET['skin'] == 'nhs') {
                    echo '<a href="' . $skin_page . '" class="first">Home</a>';
                } ?>
                <?php if (!tep_session_is_registered('customer_id')) { ?>
                    <a href="<?php echo tep_href_link(FILENAME_LOGIN, '', 'SSL'); ?>"
                       class="login"><?php echo HEADER_TITLE_LOGIN; ?></a>
                <?php } else { ?>
                    <a href="<?php echo tep_href_link("account.php", '', 'SSL'); ?>"
                       class="login"><?php echo HEADER_TITLE_MY_ACCOUNT; ?></a>
                <?php } ?>
                <a href="<?php echo tep_href_link(FILENAME_SHOPPING_CART); ?>"
                   class="shopcard"><?php echo HEADER_TITLE_SHOPPING_CART; ?></a>
                <a href="<?php echo tep_href_link(FILENAME_CHECKOUT_SHIPPING, '', 'SSL'); ?>"
                   class="checkout"><?php echo HEADER_TITLE_CHECKOUT; ?></a>
            </div>

            <?php
            if ($_GET['skin'] != 'leidapharm') {
                ?>
                <div id="menuTop">
                    <?php
                    if (in_array($_GET['skin'], $skin_white_header_array)) {
                        echo '<a href="' . tep_href_link(FILENAME_CONDITIONS) . '" class="link-white">' . LINK_HEADER_CONDITIONS . '</a>';
                        echo '<a href="' . tep_href_link("contactenadvies.php") . '" class="link-white">' . LINK_HEADER_SERVICE . '</a>';
                    } else {
                        echo '<a href="' . tep_href_link(FILENAME_CONDITIONS) . '">' . LINK_HEADER_CONDITIONS . '</a>';
                        echo '<a href="' . tep_href_link("contactenadvies.php") . '">' . LINK_HEADER_SERVICE . '</a>';
                    }
                    ?>
                </div>
            <?php } ?>

            <div class="clear"></div>
            <div id="topBar" class="clearfix">
                <div id="shopping-cart">
                    <?php
                    if ($enable_page_cache && class_exists('page_cache')) {
                        echo "<%CART_CACHE%>";
                    } else {
                        require(DIR_WS_BOXES . 'shopping_cart.php');
                    }
                    ?>
                </div>
                <div class="winkel"><a href="https://www.thuiswinkel.org/leden/de-online-drogist/certificaat"
                                       target="_blank"></a></div>
            </div>
            <div class="clear"></div>
            <div id="navigation">
                <div class="menu clearfix">
                    <ul class="menu-elements">
                        <li class="search-bar">
                            <?php echo tep_draw_form('quick_find2', tep_href_link('advanced_search_result_v3.php', '', $request_type, false), 'get', 'id=test-form'); ?>
                            <div>
                                <input type="search" id="q-form" autocomplete="off" type="text" name="keywords"
                                       value="<?php echo htmlspecialchars($_GET["keywords"]) ?>"/><input type="submit"
                                                                                                         value="ZOEK">
                            </div>
                            </form>
                        </li>
                        <?php if (!$stripped_header) { ?>
                            <li <?php if ($_SERVER['PHP_SELF'] == "/products_new.php") echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('products_new.php') ?>"><?php echo HEADER_TITLE_NIEUW; ?></a>
                            </li>
                            <li <?php if ($_SERVER['PHP_SELF'] == "/specials.php") echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('specials.php') ?>"><?php echo HEADER_TITLE_AANBIEDINGEN; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 1277) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=1277') ?>"><?php echo HEADER_TITLE_DIVERSEN; ?></a>
                            </li>
                            <li class="cadeau"><a href="<?php echo tep_href_link('index.php', 'cPath=596') ?>"><img
                                        src="./img/cadeau.jpg" width="113" height="39" alt="cadeau"></a></li>
                        <?php } ?>
                    </ul>
                </div>
                <?php if (!$stripped_header) { ?>
                    <div class="menu second clearfix">
                        <ul class="menu-elements">
                            <li <?php if ($cPath_array[0] == 964) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=964') ?>"><?php echo HEADER_TITLE_VITAMINES; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 1120) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=1120') ?>"><?php echo HEADER_TITLE_ETEN_DRINKEN; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 650) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=650') ?>"><?php echo HEADER_TITLE_AFVALLEN; ?></a>
                            </li>
                            <li <?php if (in_array($cPath_array[0], array(685, 1652, 1651, 2246, 2244, 1129, 1648, 2107))) echo 'class="active"'; ?>>
                                <a href="<?php echo tep_href_link('index.php', 'cPath=1648') ?>">Gezondheid</a></li>
                            <li <?php if ($cPath_array[0] == 361) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=361') ?>"><?php echo HEADER_TITLE_VERZORGING; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 1207) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=1207') ?>"><?php echo HEADER_TITLE_PARFUMERIE; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 1147) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=1147') ?>"><?php echo HEADER_TITLE_SEKSUALITEIT; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 598) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=598') ?>"><?php echo HEADER_TITLE_ZWANGER_BABY; ?></a>
                            </li>
                            <li <?php if ($cPath_array[0] == 917) echo 'class="active"'; ?>><a
                                    href="<?php echo tep_href_link('index.php', 'cPath=917') ?>"><?php echo HEADER_TITLE_SPORT; ?></a>
                            </li>
                        </ul>
                    </div>
                <?php } ?>
            </div>
        </div>
        <div class="breadcrumb"><?php echo $this->breadcrumb($breadcrumb, $skin);?></div>
        <div class="clear"></div>

        <!-- box: promo -->
        <?php

        if (in_array($cPath_array[0], array(650)) && $_SERVER['PHP_SELF'] == "/index.php" && SHOW_PROMOBOX == "true") { ?>
            <div class="box-promo-container">
                <a class="box-promo" href="/advanced_search_result_v3.php?keywords=xls-medical">
            <span class="promo-img">
                <img alt="XLS" width="210" height="700" src="//static.deonlinedrogist.nl/img/xl-s_sidebanner_eurokorting.jpg">
            </span>
                </a>
            </div>
        <?php } ?>
        <!-- // box: promo -->
        <!-- header_eof -->
        <?php include $this->view ?>
</body>
</html>

