<?php if (CHAT_AVAILABLE) : ?>
    <a href="javascript: window.open('https://www.deonlinedrogist.nl/fusion/visitor/index.php?/default_import/LiveChat/Chat/Request/_sessionID=/_promptType=chat/_proactive=0/_filterDepartmentID=17%2C18/_randomNumber=no1knw6lqxx99w8heyd2ywaaatuapwc2/_fullName=/_email=/', 'livechatwin', 'toolbar=0,location=0,directories=0,status=1,menubar=0,scrollbars=0,resizable=1,width=600,height=680');" class="status-icon-active">
        <span class="link-container"><span class="dod-ficon-chat"></span>
            <?php echo persoonlijke_chat ?> <span class="status-txt-online">nu online</span>
        </span> 
    </a>
<?php else : ?>
    <a href="javascript: void(0);" class="no-link">
        <span class="link-container"><span class="dod-ficon-chat"></span><?php echo persoonlijke_chat ?></span>
    </a>
<?php endif; ?>